spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_mapping
    username: root
    password: Root@1309
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true